version: "3.8"

services:
  db:
    image: postgis/postgis:latest
    container_name: postgis_container
    environment:
      POSTGRES_DB: gda_app
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/gda
    working_dir: /gda
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: gda_app
      DB_USER: usuario
      DB_PASSWORD: 1234
      DB_HOST: db

volumes:
  pgdata:
