from .municipio_serializers import MunicipioSerializer
from .logradouro_serializers import LogradouroSerializer
#from .log_cor_serializers import LogCorSerializer
from .comarca_serializers import ComarcaSerializer