# Generated by Django 5.1.3 on 2024-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('comum', 'Cidadão'), ('operador', 'Operador'), ('adm', 'Administrador')], default='comum', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
