# Generated by Django 5.1.3 on 2025-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_self_registration_user_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
