# Generated by Django 5.1.3 on 2025-05-03 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_reset_token_user_reset_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Conta Ativada'),
        ),
        migrations.AddField(
            model_name='user',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfil/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagem de Perfil'),
        ),
    ]
