# Generated by Django 5.1.3 on 2025-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_ativo_user_imagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conf_not_email',
            field=models.BooleanField(default=False, verbose_name='Receber notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='conf_not_newdenun',
            field=models.BooleanField(default=False, verbose_name='Notificar novas denúncias'),
        ),
        migrations.AddField(
            model_name='user',
            name='conf_not_push',
            field=models.BooleanField(default=False, verbose_name='Receber notificações push'),
        ),
        migrations.AddField(
            model_name='user',
            name='conf_tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=20, verbose_name='Tema preferido'),
        ),
    ]
