# Generated by Django 5.1.3 on 2025-05-10 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_user_conf_not_email_user_conf_not_newdenun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de criação'),
        ),
    ]
