# Generated by Django 5.1.3 on 2024-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denuncias_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="status",
            field=models.CharField(
                choices=[("Pendente", "Pendente"), ("Resolvido", "Resolvido")],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
