# Generated by Django 5.1.3 on 2024-11-23 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enderecos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pendente", "Pendente"), ("Resolvido", "Resolvido")],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enderecos.municipio",
                        verbose_name="Município relacionado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
