# Generated by Django 5.1.3 on 2024-12-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
        ('enderecos', '0004_alter_logradouro_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denunciante_denuncias', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logradouro_denuncias', to='enderecos.logradouro', verbose_name='Endereço relacionado'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='infrator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Infrator'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='nr_endereco',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numeral'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_denuncias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='enderecos.municipio', verbose_name='Município relacionado'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('analise', 'Em análise'), ('fila', 'Aguardando atendimento'), ('concluida', 'Atendimento concluído'), ('negada', 'Denúncia rejeitada')], default='analise', max_length=20),
        ),
    ]
