# Generated by Django 5.1.3 on 2024-12-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0004_denuncia_anonima_denuncia_localizacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="localizacao",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Coordenada geográfica (GeoJSON)"
            ),
        ),
    ]
