# Generated by Django 5.1.3 on 2024-12-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0005_alter_denuncia_localizacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="denunciante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="denunciante_denuncias",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Denunciante",
            ),
        ),
    ]
