# Generated by Django 5.1.3 on 2025-05-05 20:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_alter_denuncia_denunciante'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='aprovada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Aprovada por autoridade'),
        ),
        migrations.RemoveField(
    model_name='denuncia',
    name='localizacao',
),
migrations.AddField(
    model_name='denuncia',
    name='localizacao',
    field=django.contrib.gis.db.models.PointField(
        geography=True,
        verbose_name='Localização geográfica (latitude/longitude)',
        null=True,
        blank=True
    ),
)
    ]
