# Generated by Django 5.1.3 on 2025-05-06 22:26

import denuncias.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_denuncia_aprovada_alter_denuncia_localizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexo',
            options={'ordering': ['-data_upload']},
        ),
        migrations.AlterModelOptions(
            name='statushistorico',
            options={'ordering': ['-data_alteracao']},
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to=denuncias.models.anexo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do envio'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.denuncia', verbose_name='Denúncia'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('analise', 'Em análise'), ('fila', 'Aguardando atendimento'), ('atendimento', 'Em atendimento'), ('concluida', 'Atendimento concluído'), ('negada', 'Denúncia rejeitada')], db_index=True, default='analise', max_length=20, verbose_name='Status da denúncia'),
        ),
        migrations.AlterField(
            model_name='statushistorico',
            name='data_alteracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração'),
        ),
        migrations.AlterField(
            model_name='statushistorico',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='denuncias.denuncia', verbose_name='Denúncia'),
        ),
        migrations.AlterField(
            model_name='statushistorico',
            name='status',
            field=models.CharField(choices=[('analise', 'Em análise'), ('fila', 'Aguardando atendimento'), ('atendimento', 'Em atendimento'), ('concluida', 'Atendimento concluído'), ('negada', 'Denúncia rejeitada')], max_length=20, verbose_name='Status'),
        ),
    ]
