# Generated by Django 5.1.3 on 2025-05-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_alter_anexo_options_alter_statushistorico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
