# Generated by Django 5.1.3 on 2025-05-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0009_denuncia_bairro'),
        ('fatosesub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='fato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fato_denuncias', to='fatosesub.fato', verbose_name='Fato relacionado'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_denuncias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='subfato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfato_denuncias', to='fatosesub.subfato', verbose_name='Subfato relacionado'),
        ),
    ]
