# Generated by Django 5.1.3 on 2025-05-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0010_alter_denuncia_fato_alter_denuncia_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denuncia_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='denuncias.denuncia', verbose_name='Denúncia relacionada'),
        ),
    ]
