# Generated by Django 5.1.3 on 2025-05-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0011_denuncia_denuncia_ref'),
        ('enderecos', '0007_alter_logcor_logradouro_alter_logcor_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denunciante_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='endereco_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fato_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='municipio_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='subfato_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logradouro_denuncias', to='enderecos.logradouro', verbose_name='Endereço relacionado'),
        ),
    ]
