# Generated by Django 5.1.3 on 2024-11-23 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enderecos", "0002_logradouro_logcor"),
    ]

    operations = [
        migrations.AddField(
            model_name="logradouro",
            name="cidade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="enderecos.municipio",
                verbose_name="Cidade relacionada",
            ),
            preserve_default=False,
        ),
    ]
