# Generated by Django 5.1.3 on 2024-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enderecos", "0003_logradouro_cidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logradouro",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome do Logradouro"),
        ),
    ]
