# Generated by Django 5.1.3 on 2025-05-11 23:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0004_alter_logradouro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcor',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordenada geográfica'),
        ),
        migrations.AddField(
            model_name='logradouro',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
    ]
