# Generated by Django 5.1.3 on 2025-05-11 23:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0005_logcor_localizacao_logradouro_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcor',
            name='dados',
        ),
        migrations.RemoveField(
            model_name='logcor',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='logcor',
            name='trecho',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
