# Generated by Django 5.1.3 on 2025-05-12 02:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0006_remove_logcor_dados_remove_logcor_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcor',
            name='logradouro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enderecos.logradouro', verbose_name='Logradouro relacionado'),
        ),
        migrations.AlterField(
            model_name='logcor',
            name='trecho',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
